name: GitHub-Profile-Summary-Cards

on:
  schedule: # Автоматический запуск каждую полночь
    - cron: "0 0 * * *"
  workflow_dispatch: # Позволяет запускать генерацию вручную

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v5
      
      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_PAT }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME: default

      - name: Deploy to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update profile summary cards" || exit 0
          git push
